Project sprint 4
DeVIn4I/MovieQuiz-ios pull request #2
Opened 2022-09-27 17:13 UTC by DeVIn4I

2022-09-27 18:46 UTC, ABashkirova requested changes
Проект запускается и работает, однако есть несколько моментов по верстке, которые нужно исправить

2022-09-27 18:46 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        }
В продакшен коде не рекомендуется использовать tag. Это не самый прозрачный и понятный код. Если выбирать между двумя функциями yesButtonClick-noButtonClick и тегами, предпочтение отдают двум отдельным функциям. 

Предлагаю заменить и не возвращаться к тегам больше никогда, пока перед вами не встанет задача ну где действительно без них не обойтись :) 

Также, замечу, что switch в этом случае тоже не удачное решение, так как использованный default c брейком зачастую тоже считается кодом с запашком ([code smells](https://ru.wikipedia.org/wiki/Код_с_запашком)) 
и даже если его переписать, получается, что код не разделенный на два нажатия, подразумевает один возможный кейс с выходом из функции, что тоже вам не нужно :) более плоский код (без ветвлений) обычно содержит меньше багов

```suggestion
    @IBAction private func clickAnswer(_ sender: UIButton) {
        let currentQuest = questions[currentQuestionIndex]
        var answerQuestion: Bool 
        if sender.tag == 0 {
            answerQuestion = false
        } else if sender.tag == 1 {
            answerQuestion = true
          } else {
          return // дальше нечего показывать, непредвиденное состояние
          }
       
```

2022-09-27 18:46 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        imageView.layer.cornerRadius = 20
cornerRadius и masksToBounds - разовые настройки, их можно сделать единожды в viewDidLoad

2022-09-27 18:46 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        DispatchQueue.main.asyncAfter(deadline: .now() + 1.0) { self.showNextQuestionOrResults() }
замечу, что это асинхронный код, который пользователь может инициировать многократно, если зажмет несколько раз по кнопке до тех пор пока не появится следующий вопрос. 

Это приводит к неверному состоянию счетчика и результата квиза. Исправить можно заблокировав [кнопки пользователю ](https://developer.apple.com/documentation/uikit/uicontrol/1618217-isenabled)

2022-09-27 21:16 UTC, DeVIn4I commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        DispatchQueue.main.asyncAfter(deadline: .now() + 1.0) { self.showNextQuestionOrResults() }
<img width="748" alt="image" src="https://user-images.githubusercontent.com/79083903/192635844-f5063642-fc16-4eaf-b8b4-e6d3a7d4ec83.png">

На курсе пока не было материала про диспетчер задач)
Информацию принял, спасибо!

2022-09-27 21:45 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            self.yesButton.isEnabled = true
👍

2022-09-27 21:48 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            }
В будущих спринтах вам будут рассказывать про слабый список захвата. Здесь используется замыкание, которое на данный момент сильно захватывает ссылку на класс. Такой код может вызывать утечки памяти. Без подробностей, по желанию, предлагаю добавить `[weak self]`. Такая добавка потребует от вас вызвать методы и свойства класса через `self?.` Поэтому внутренности предлагаю вынести в отдельную функцию. Например, так:

```suggestion
            style: .default) { [weak self] _ in
                self?.restartQuiz()
            }
```

2022-09-27 21:50 UTC, ABashkirova commented on MovieQuiz.xcodeproj/project.pbxproj
> +		B3C7F62028D484D00058A42E /* YS Display-Bold.ttf */ = {isa = PBXFileReference; lastKnownFileType = file; path = "YS Display-Bold.ttf"; sourceTree = "<group>"; };
Все еще не хватает галочки напротив target:
<img width="1512" alt="Screenshot 2022-09-28 at 00 49 37" src="https://user-images.githubusercontent.com/20269264/192642225-abcd86d1-855c-4346-a626-6d69b38632d3.png">

2022-09-27 21:54 UTC, ABashkirova commented on MovieQuiz.xcodeproj/project.pbxproj
> +		B3C7F62028D484D00058A42E /* YS Display-Bold.ttf */ = {isa = PBXFileReference; lastKnownFileType = file; path = "YS Display-Bold.ttf"; sourceTree = "<group>"; };
Эту правку жду, чтобы принять работу

2022-09-28 05:39 UTC, DeVIn4I commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            }
Буду знать, спасибо)

2022-09-28 05:41 UTC, DeVIn4I commented on MovieQuiz.xcodeproj/project.pbxproj
> +		B3C7F62028D484D00058A42E /* YS Display-Bold.ttf */ = {isa = PBXFileReference; lastKnownFileType = file; path = "YS Display-Bold.ttf"; sourceTree = "<group>"; };
![dQZ2LWCzg20](https://user-images.githubusercontent.com/79083903/192696833-ab7b4aa2-a6dd-4c9b-b881-11537c326044.jpeg)

2022-09-28 11:57 UTC, ABashkirova commented on MovieQuiz.xcodeproj/project.pbxproj
> +		B3C7F62028D484D00058A42E /* YS Display-Bold.ttf */ = {isa = PBXFileReference; lastKnownFileType = file; path = "YS Display-Bold.ttf"; sourceTree = "<group>"; };
😄

2022-09-28 17:11 UTC, merged