Project sprint 6
DeVIn4I/MovieQuiz-ios pull request #4
Opened 2022-10-27 18:29 UTC by DeVIn4I

2022-10-27 18:54 UTC, ABashkirova requested changes
Хорошая работа. Давайте поправим retain cycle, дополнительно вы можете обработать ошибочные состояния.

2022-10-27 18:54 UTC, ABashkirova commented on MovieQuiz/Models/MostPopularMovies.swift
> +    let errorMessage: String
Обратите внимание, что здесь может прийти сообщение об ошибке. Например, когда апи ключ истек или использованы все попытки на получение фильмов, тогда список фильмов будет пустым. Приложение будет выглядеть сломанным

2022-10-27 18:54 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    @IBOutlet private weak var activityIndicator: UIActivityIndicatorView!
👍

2022-10-27 18:54 UTC, ABashkirova commented on MovieQuiz/Services/QuestionFactory.swift
> +    private let delegate: QuestionFactoryDelegate
Кажется, в учебнике забыли исправить это место :( weak var было правильно, а сейчас retain cycle создан

2022-10-27 18:54 UTC, ABashkirova commented on MovieQuiz/Services/QuestionFactory.swift
> +                print("Ошибка загрузки изображения")
Обратите внимание, что если постер не загрузится, то вы покажете новый вопрос с неправильным изображением. Пользователь не сможет правильно ответить на вопрос без постера

2022-10-28 12:16 UTC, DeVIn4I commented on MovieQuiz/Services/QuestionFactory.swift
> +    private let delegate: QuestionFactoryDelegate
Подскажите, пожалуйста, как можно проверить проект на RC? есть ли какие нибудь инструменты или можно как-то в самом xcode это увидеть?

2022-10-28 14:21 UTC, ABashkirova commented on MovieQuiz/Services/QuestionFactory.swift
> +    private let delegate: QuestionFactoryDelegate
К сожалению, на текущем этапе проверить будет сложно, чтобы воспроизвести, вам нужно чтобы вью-контроллер попытался деинициализироваться. Деинициализация происходит, когда экран закрывается. 

Вам надо воспроизвести ситуацию открытия-закрытия контроллера, такое можно сделать на навигационном стеке или на модальных презентациях. 
Обычно повторяют открыть-закрыть экран, ставят на паузу в дебаг меню и смотрят сколько ссылок в Xcode осталось через Memory Graph

<img width="412" alt="Screenshot 2022-10-28 at 18 16 43" src="https://user-images.githubusercontent.com/20269264/198638743-242b90fc-86df-4663-9980-e6ebe7da9ae8.png">
Также, у Xcode есть профайлеры, с помощью которых можно также отслеживать утечки памяти. 
Xcode > Open Developer Tool > Instruments 

<img width="836" alt="Screenshot 2022-10-28 at 18 18 00" src="https://user-images.githubusercontent.com/20269264/198640266-beab823e-ef39-4447-a822-57b50d7da635.png">

Вы можете подождать второго модуля, там будет гораздо проще это поведение проверить, либо же найти информацию самостоятельно :)

2022-10-28 14:30 UTC, DeVIn4I commented on MovieQuiz/Services/QuestionFactory.swift
> +    private let delegate: QuestionFactoryDelegate
Большое спасибо за такой развернутый ответ! ^_^

2022-10-29 04:34 UTC, ABashkirova approved these changes
Супер, работа принята!

2022-10-29 04:34 UTC, ABashkirova commented on MovieQuiz/Resources/Info.plist
> +		<string>YS Display-Thin</string>
Если вы все шрифты не собираетесь использовать, предлагаю оставить только то что используется

2022-10-29 04:34 UTC, ABashkirova commented on MovieQuiz/Services/QuestionFactory.swift
> +                }
Не критично, но, здесь приложение вернет ошибку на UI и дополнительно вернет новый вопрос без текста. Нужен выход из функции, как мне кажется

2022-11-10 10:46 UTC, merged